### ISSUE TITLE
[BUG] OpenWeather plugin doesn't work anymore!

### ISSUE THREAD

**Issue by bambalooon** [denzilferreira/com.aware.plugin.openweather#2]
OpenWeatherMap probably changed API and now it requires API key, which is missing in Aware requests.
OpenWeatherMap returns:

```
Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.
```

You probably need to create account for Aware application.
Please let me now when you fix it or if I've done something wrong.
[How to use API key](http://www.openweathermap.org/appid)

Best regards,
K.B.

**Comment by denzilferreira** [comment]
Thanks for reporting. We'll fix it!

Denzil;

**Comment by denzilferreira** [comment]
I've updated the source of this plugin, but I need to test it tomorrow. You can add your own API key on the plugin's settings.
